UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Kickback/0.jpg' WHERE name = 'Coice Polia';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Bridge/0.jpg' WHERE name = 'Hip Thrust com Barra';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Lateral_Raise/0.jpg' WHERE name = 'Elevação Lateral Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Lateral_Raise/0.jpg' WHERE name = 'Elevação Lateral Polia';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Shrug/0.jpg' WHERE name = 'Encolhimento Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Rear_Delt_Fly/0.jpg' WHERE name = 'Rear Delt Machine';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Shoulder_Press/0.jpg' WHERE name = 'Desenvolvimento Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press_Calf_Raise/0.jpg' WHERE name = 'Panturrilha Leg Press';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg' WHERE name = 'Panturrilha Máquina em Pé';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg' WHERE name = 'Panturrilha Sentada';
