UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg' WHERE name = 'Russian Twist';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Machine_Hip_Abduction/0.jpg' WHERE name = 'Abdução Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Machine_Hip_Adduction/0.jpg' WHERE name = 'Adução Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Preacher_Curl/0.jpg' WHERE name = 'Rosca Scott Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg' WHERE name = 'Abdominal Polia';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Machine_Crunch/0.jpg' WHERE name = 'Crunch Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Raise/0.jpg' WHERE name = 'Elevação de Pernas';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Machine_Row/0.jpg' WHERE name = 'Remada Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg' WHERE name = 'Remada Polia Sentada';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Pulldown/0.jpg' WHERE name = 'Pulldown';
