UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg' WHERE name = 'Russian Twist';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Machine_Hip_Abduction/0.jpg' WHERE name = 'Abdução Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Machine_Hip_Adduction/0.jpg' WHERE name = 'Adução Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Preacher_Curl/0.jpg' WHERE name = 'Rosca Scott Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg' WHERE name = 'Abdominal Polia';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Machine_Crunch/0.jpg' WHERE name = 'Crunch Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Raise/0.jpg' WHERE name = 'Elevação de Pernas';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Machine_Row/0.jpg' WHERE name = 'Remada Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg' WHERE name = 'Remada Polia Sentada';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Pulldown/0.jpg' WHERE name = 'Pulldown';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Kickback/0.jpg' WHERE name = 'Coice Polia';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Bridge/0.jpg' WHERE name = 'Hip Thrust com Barra';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Lateral_Raise/0.jpg' WHERE name = 'Elevação Lateral Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Lateral_Raise/0.jpg' WHERE name = 'Elevação Lateral Polia';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Shrug/0.jpg' WHERE name = 'Encolhimento Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Rear_Delt_Fly/0.jpg' WHERE name = 'Rear Delt Machine';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Shoulder_Press/0.jpg' WHERE name = 'Desenvolvimento Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press_Calf_Raise/0.jpg' WHERE name = 'Panturrilha Leg Press';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg' WHERE name = 'Panturrilha Máquina em Pé';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg' WHERE name = 'Panturrilha Sentada';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Chest_Press/0.jpg' WHERE name = 'Supino Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Bench_Press/0.jpg' WHERE name = 'Supino Smith';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Pec_Deck_Fly/0.jpg' WHERE name = 'Peck Deck';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/0.jpg' WHERE name = 'Crucifixo com Halteres';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg' WHERE name = 'Flexão de Braço';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg' WHERE name = 'Crossover Polia Alta';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Chest_Press/0.jpg' WHERE name = 'Chest Press';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Romanian_Deadlift/0.jpg' WHERE name = 'Stiff com Halteres';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg' WHERE name = 'Mesa Flexora';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg' WHERE name = 'Hack Machine';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg' WHERE name = 'Leg Press 45';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lever_Triceps_Extension/0.jpg' WHERE name = 'Tríceps Máquina';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Triceps_Pushdown/0.jpg' WHERE name = 'Tríceps Polia Barra';
UPDATE public.exercises SET gif_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Triceps_Pushdown_Rope/0.jpg' WHERE name = 'Tríceps Polia Corda';
UPDATE public.exercises SET gif_url = 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80' WHERE gif_url IS NULL OR gif_url = '';